### ISSUE TITLE
好像不支持多终端同时使用？

### ISSUE THREAD

**Issue by godmoon** [hacdias/webdav#111]
用来分享电影，一个终端在看电影，另一个终端好像就看不了了，退出前一个终端，后一个终端才可以使用。

**Comment by AdminHcat** [comment]
Why not communicate in English? Not everyone can speak Chinese

**Comment by Whichbfj28** [comment]
也不是每个人都说英语。。

**Comment by AdminHcat** [comment]
> 也不是每个人都说英语。。

这里是Github是国际化社区不是某贴吧，英语是国际开源社区交流的标准语，更何况这是个英文项目，认真严肃地写issue是对开源项目和维护者最起码的尊重，项目维护者也是人时间是有限的，面对这样没有礼貌的 issue，我认为应该直接关闭

**Comment by SCGabriel** [comment]
> 也不是每个人都说英语。。

你是来解决问题还是来制造问题？作者根本不懂中文你想不想作者看懂你的问题？你写中文被英文母语的人无视正常。

**Comment by hacdias** [comment]
There's a lot of variables here: are they running through the same user? Different user? What's the host operating system? What client are you using? Etc. WebDAV protocol uses locks to prevent users from changing the same file at the same time, and that may be one of the things you're hitting here.

Please let me know if this is still a problem and I will re-open this.
