### ISSUE TITLE
[docker support] Im creating a docker repo for unraid and other nas os

### ISSUE THREAD

**Issue by VergilGao** [hacdias/webdav#112]
https://github.com/VergilGao/docker-webdav
https://hub.docker.com/r/vergilgao/webdav
https://ghcr.io/vergilgao/webdav

need more time to write documents...

if you are an unraid user, just mount your data volume to /data and /mnt/user/appdata/webdav to /config
if you want to modify the config file, you can find it at /mnt/user/appdata/webdav/custom-config.yml (depends on where you mount the /config path)

in default, the webdav run as user 99:100 and all file permission will be set to user 99:100, and the umask is 000.
if you are not an unraid user, just set the environment variables UID GID UMASK.
you can set the  environment variable TZ to get local time display on log output.

**Comment by skyshenma** [comment]
大佬方便吧参数不齐吗，感谢

**Comment by VergilGao** [comment]
我换用nextcloud了所以这个不维护了。
