### ISSUE TITLE
Keepass cannot modify files on the WebDAV server

### ISSUE THREAD

**Issue by Ausli** [hacdias/webdav#123]
I suspect that the delete command cannot delete the file, which makes it impossible to modify the KeePass file。

![image](https://user-images.githubusercontent.com/70201547/164974235-842e59bb-7154-4bb9-a2aa-2d31fe94f0b5.png)

**Comment by hacdias** [comment]
You get a 404, so I would guess the file does not exist. Have you tried using a differnt application to see the files you have there and see if the file actually exists?

In the meanwhile, I've rewritten this package and fixed quite a few bugs. Please try again with the new version, and feel free to open a new issue if this is still a problem.
