### ISSUE TITLE
Is it possible to complete permission authentication by url parameter

### ISSUE THREAD

**Issue by eastarpen** [hacdias/webdav#126]
**Thanks for the wonderful program!**

It seems that site server certification in **Request Header** with property `Authorization: Basic YmFzaWM6YmFzaWM=`

In my case, I cannot modify the request header, only to get resources by url

so, is  it possible to complete permission authentication by url like below?

```
http://ip:port/path/to/resource?user=user&password=password
```

**Thanks for the reply**

**Comment by mohammed90** [comment]
This form should work:

```
http://user:password@ip:port/path/to/resource
```

**Comment by eastarpen** [comment]
> This form should work:
> 
> ```
> http://user:password@ip:port/path/to/resource
> ```

Thanks, it does work
