### ISSUE TITLE
Error running on MiWiFi-R1D, prompting "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by windmaple233** [hacdias/webdav#133]
![image](https://user-images.githubusercontent.com/36031837/181189122-88394fb4-653f-4761-9f77-9dd4827b9b4a.png)

This is a home router "MiWiFi-R1D". OS is openwrt. The CPU is BCM4709, ARMv7 architecture.

**Comment by yuanjie1853** [comment]
you should download linux-armv5。
