### ISSUE TITLE
not issue，a question，config中的路径如何才能支持通配符*

### ISSUE THREAD

**Issue by ubun222** [hacdias/webdav#135]
我在安卓使用您的webdav服务，tf卡路径为*-*，因为每次格式化都会变化挂载文件夹的名称。如果能支持通配符*就不需要每次更名。方便很多。

**Comment by SCGabriel** [comment]
这个项目的维护者没有一个会普通话，请用英文再提问一遍。另外咱觉得你这是挂载的问题，在linux上即使格式化，挂载的路径也不会变更，这个是你安卓软件设置问题，没有必要的需求。
