### ISSUE TITLE
Debian as a server and Windows 11 as a client, then windows can not connect to server

### ISSUE THREAD

**Issue by Pidbid** [hacdias/webdav#142]
hey guys 
I take the webdav server (http) on debian  and then I want connect the server at windows,I can open with browser from "IP:PORT", and the webpage seems like xml code ...
next I have tryed "map network driver" and "Add a network location" options on wondows , it seems not working. 
what should I do ？
Thanks a lot.

**Comment by mohammed90** [comment]
The issue is with on Windows side. Perhaps some further configuration parameters need to be set. I found this, but I cannot validate if this is truly the issue or not:
https://docs.qnap.com/operating-system/qts/4.5.x/en-us/GUID-31D5B05F-F29E-4D61-9758-C8CF839C14FD.html

**Comment by Pidbid** [comment]
Thinks a lot.
