### ISSUE TITLE
There is a problem with Windows mapping

### ISSUE THREAD

**Issue by TDCBQ** [hacdias/webdav#146]
http2: server: error reading preface from client 192.168.188.132:58945: read tcp 192.168.122.93:21235->192.168.188.132:58945: read: connection reset by peer
2022/12/14 09:58:57 http2: server: error reading preface from client 192.168.188.132:58946: read tcp 192.168.122.93:21235->192.168.188.132:58946: read: connection reset by peer
2022/12/14 09:58:57 http: TLS handshake error from 192.168.188.132:58947: EOF
2022/12/14 09:59:10 http2: server: error reading preface from client 192.168.188.132:58959: read tcp 192.168.122.93:21235->192.168.188.132:58959: read: connection reset by peer
![image](https://user-images.githubusercontent.com/37407560/207566560-42b2c661-6481-41a1-871d-44ab3f584054.png)

The certificate has been downloaded, but the TLS handshake will be turned off by Windows. How can I solve this problem

**Comment by hacdias** [comment]
I'm not sure what the problem here is, nor have I ever seen this. Please re-open if this is still a problem. Nevertheless, it's likely related to your configuration and not this package.

**Comment by TDCBQ** [comment]
sorry,its's my misstake

**Comment by OhnkytaBlabdey** [comment]
i meet the same error, how to fix it?
