### ISSUE TITLE
Revive Webdav Package

### ISSUE THREAD

**Issue by hacdias** [hacdias/webdav#151]
I decided to revive this package. I still see people adding stars regularly, and it's quite a small package to maintain. There are quite a few steps that need to be followed and it will likely take some time to finish, but here's what I feel like needs to be done:

- [x] https://github.com/hacdias/webdav/pull/153
- [x] https://github.com/hacdias/webdav/pull/152
- [x] https://github.com/hacdias/webdav/pull/154
- [x] #157 
- [x] Release v4.3.0 to test release flow
    - [x] Fix Docker `version` command
- [x] Update README:
   - [x] Install instructions: Go, Docker
   - [x] Service in README instead of file
   - [x] Improved coinfig file explanation
- [x] Go over issues and see what can be cleaned and what can be followed up upon and set list for v5.

**Comment by AoThen** [comment]
Thank you very much for you. This project is fantastic, like it

**Comment by holzora** [comment]
Wow!
