### ISSUE TITLE
Lastest docker images: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by HuLian21** [hacdias/webdav#165]
Hello, I’m use this docker image for years, I am very grateful. And yesterday the watchtower automatically update docker container, I got an panic error. 

`ubuntu@ubuntu:/srv/docker/webdav$ cat docker-compose.yaml
version: '3'
services:
  webdav:
    restart: unless-stopped
    container_name: webdav
    image: hacdias/webdav:latest
    volumes:
      - /media/sharefolder:/media/sharefolder
      - /srv/docker/webdav/config:/config
      - /home/ubuntu/.config/cert:/cert
    command: --config /config/webdav.config.yml
    ports:
      - 28222:28222
ubuntu@ubuntu:/srv/docker/webdav$ docker compose down
WARN[0000] /srv/docker/webdav/docker-compose.yaml: `version` is obsolete 
[+] Running 2/2
 ✔ Container webdav        Removed                        0.4s 
 ✔ Network webdav_default  Re...                          0.4s 
ubuntu@ubuntu:/srv/docker/webdav$ docker compose up
WARN[0000] /srv/docker/webdav/docker-compose.yaml: `version` is obsolete 
[+] Running 2/2
 ✔ Network webdav_default  Cr...                          0.2s 
 ✔ Container webdav        Created                        0.2s 
Attaching to webdav
webdav  | 2024-07-23T00:52:06.652Z      info    listening     {"address": "[::]:28222"}
webdav  | 2024/07/23 00:52:11 http: panic serving 172.19.0.1:56824: runtime error: invalid memory address or nil pointer dereference
webdav  | goroutine 20 [running]:
webdav  | net/http.(*conn).serve.func1()
webdav  |       /usr/local/go/src/net/http/server.go:1903 +0xbe
webdav  | panic({0x8d9460?, 0xd2b7b0?})
webdav  |       /usr/local/go/src/runtime/panic.go:770 +0x132
webdav  | github.com/hacdias/webdav/v4/lib.(*Handler).ServeHTTP(0xc0001136c0?, {0xa244d8, 0xc0001b62a0}, 0xc000155d40)
webdav  |       /webdav/lib/handler.go:73 +0x3c
webdav  | github.com/hacdias/webdav/v4/lib.NewHandler.(*Cors).Handler.func1({0xa244d8, 0xc0001b62a0}, 0xc000155d40)
webdav  |       /go/pkg/mod/github.com/rs/cors@v1.11.0/cors.go:289 +0x184
webdav  | net/http.HandlerFunc.ServeHTTP(0x46a519?, {0xa244d8?, 0xc0001b62a0?}, 0xc0000a5b68?)
webdav  |       /usr/local/go/src/net/http/server.go:2171 +0x29
webdav  | net/http.serverHandler.ServeHTTP({0xc0001b8ba0?}, {0xa244d8?, 0xc0001b62a0?}, 0x6?)
webdav  |       /usr/local/go/src/net/http/server.go:3142 +0x8e
webdav  | net/http.(*conn).serve(0xc00014e630, {0xa253e8, 0xc0001b8900})
webdav  |       /usr/local/go/src/net/http/server.go:2044 +0x5e8
webdav  | created by net/http.(*Server).Serve in goroutine 18
webdav  |       /usr/local/go/src/net/http/server.go:3290 +0x4b4
webdav  | 2024/07/23 00:53:54 http: panic serving  `

**Comment by HuLian21** [comment]
Version tag 4.2 is functioning correctly.

**Comment by hacdias** [comment]
Sorry for this. Yes, it is already fixed. I'm planning on adding more automated tests to avoid this in the future.
