### ISSUE TITLE
sharing whole partition

### ISSUE THREAD

**Issue by ofsahin** [hacdias/webdav#17]
hello,

i am on windows. when i share the whole partition like this:
`	webdav /webdav/c/ {
	    scope       c:\
	    modify      true
}
`
i get httpcode 401
but when i stop caddy, change the scope to a directory
`	webdav /webdav/c/ {
	    scope       c:\caddy\
	    modify      true
}
`
and restart it, everything works smoothly. this is same for different drive letters.
whats your take on this?

**Comment by hacdias** [comment]
I'm closing this as it is unclear whether or not this is still a problem. If this is, please open a new issue.
