### ISSUE TITLE
allow disabling auth again even with list of users (delegating authentication)

### ISSUE THREAD

**Issue by Cyrix126** [hacdias/webdav#174]
From the [5.0.0](https://github.com/hacdias/webdav/releases/tag/v5.0.0) release note:

> auth option no longer exists and it will be inferred from the users.

My setup was using nginx to authenticate users with a LDAP server and forwarding the header X-Forwarded-For so that webdav recognize the user and give gim the right directory for him. I was using auth: false in the config of webdav.

With the latest version,  I can't do this anymore since authentication is mandatory.
Please allow to again disable authentication so we can transfer the authentication to another service if we need to.

**Comment by mohammed90** [comment]
The README says:

> # The list of users. If users is empty, then there will be no authentication.

Have you tried that?

**Comment by Cyrix126** [comment]
> The README says:
> 
> > The list of users. If users is empty, then there will be no authentication.
> 
> Have you tried that?

I need the list to give them access to custom path based on their username.

**Comment by hacdias** [comment]
> My setup was using nginx to authenticate users with a LDAP server and forwarding the header X-Forwarded-For so that webdav recognize the user and give gim the right directory for him. I was using auth: false in the config of webdav.

This is a very interesting use case. But how does this play with basic authentication? Or do you also proxy the authentication using the username from LDAP with no password?

**Comment by Cyrix126** [comment]
>  It seems you were relying on something we had built in in version 4.2.0 and older

Correct. I wanted to update it since I had trouble with missing files/directories, (possibly unrelated to this webdav server) and saw the breaking changes.
> I assume you're proxying the basic auth user. 
Here's my setup:
I'm using [lldap](https://github.com/lldap/lldap) and protect requests in nginx with (nginx-ldap-auth-service)[https://pypi.org/project/nginx-ldap-auth-service] and with nginx module [ngx_http_auth_request_module](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html).

I did this configuration a while ago and I'm not sure if everything is required, I intend to switch to [kanidm](https://github.com/kanidm/kanidm), but principal is the same: check basic and if valid send header with username to backend service.

```
auth_ldap "Forbidden";
# webdav here is name of ldap config included in nginx to check if basic auth username is in group and password is valid.
        auth_ldap_servers webdav; 
  location / {
    proxy_pass http://127.0.0.1:xxxx; # port used by webdav service
    proxy_redirect        off;
    proxy_set_header      Host $http_host;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header      X-Forwarded-Proto $scheme;
    proxy_set_header      X-Forwarded-Ssl on;
    proxy_set_header      Connection "";
    proxy_pass_header     Date;
    proxy_pass_header     Server;
  }
```
> I see two options:

(you mean three).

Option 2 is indeed the best, option 3 is impossible since password in the authorizing service are unknown (hashed).

**Comment by hacdias** [comment]
@Cyrix126 I indeed meant three, I updated the comment quite a few times. I will take a better look at #175 and potentially release it today/tomorrow.
