### ISSUE TITLE
Webdav fails when it encounters a socket file

### ISSUE THREAD

**Issue by dhaavi** [hacdias/webdav#18]
When using this Caddyfile for testing, I encountered an error:

    localhost {

      webdav /webdav {
        scope /tmp
      }

    }

I have a socket file unter `/tmp/`, this is what caddy returned:

    <?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:">[...]</D:multistatus>Internal Server Error

Note: I snipped out the content and replaced it with `[...]`

Interestingly, it did send a valid xml, but with `Internet Server Error` attached.
The xml of course only included records until it (presumably) hit the socket file, at which point it failed.

Sorry for the simple issue. I'll gladly do more testing and look into the source myself later.

**Comment by vitaliy-kuzmich** [comment]
@hacdias hey, wow  this webdav server just works! exactly what I need! Did you tell that you are  using official webdav ? I tried it, and it seems its broken, there issue with depth, actually go implementation thinks that -1 is a infinite depth, but it is not. Well, if you do not mind, I will include your webdav server in @browsefile project(which is actually based on filebrowser as well :1st_place_medal:  haha :) )
