### ISSUE TITLE
Reboot frequently in docker, with error code

### ISSUE THREAD

**Issue by dc3000** [hacdias/webdav#182]
log:
[34mINFO[0m	caught signal, shutting down	{"signal": "terminated"}

then reboot ,again & again.. per one minutes!

**Comment by hacdias** [comment]
This log message means that your Docker container is receiving system signals for shutdown. This happens when you press CTRL+C for example. However, this should not happen the way you're describing. Most likely you have some other process causing this, as I can't reproduce this.

What's your configuration? Your docker configuration? In which system are you running this?

**Comment by dc3000** [comment]
System：ZSpace-NAS，
DockerVersion：20.10.2
Configuration：
`address: 0.0.0.0
port: 6065

# TLS-related settings if you want to enable TLS directly.
tls: false
cert: cert.pem
key: key.pem

# Prefix to apply to the WebDAV path-ing. Default is '/'.
prefix: /

# Enable or disable debug logging. Default is 'false'.
debug: true

# Disable sniffing the files to detect their content type. Default is 'false'.
noSniff: true

# The directory that will be able to be accessed by the users when connecting.
# This directory will be used by users unless they have their own 'directory' defined.
# Default is '.' (current directory).
directory: /data

# The default permissions for users. This is a case insensitive option. Possible
# permissions: C (Create), R (Read), U (Update), D (Delete). You can combine multiple
# permissions. For example, to allow to read and create, set "RC". Default is "R".
permissions: CRUD

# The default permissions rules for users. Default is none.
rules: []

# The list of users. If the list is empty, then there will be no authentication.
# Otherwise, basic authentication will automatically be configured.
#
# If you're delegating the authentication to a different service, you can proxy
# the username using basic authentication, and then disable webdav's password
# check using the option:
#
# noPassword: true
users:
  # Example 'admin' user with plaintext password.
  - username: admin
    password: admin

# Logging configuration
log:
  # Logging format ('console', 'json'). Default is 'console'.
  format: console
  # Enable or disable colors. Default is 'true'. Only applied if format is 'console'.
  colors: false
  # Logging outputs. You can have more than one output. Default is only 'stderr'.
  outputs:
  - stderr`

**Comment by dc3000** [comment]
This is a great project!But i cant find the reason of the problem with many trys.It seams ssh terminal is not supported.Whether the signal can be ignored by the code?

**Comment by hacdias** [comment]
> Whether the signal can be ignored by the code?

No, that would defeat the purpose.

> It seams ssh terminal is not supported.

What do you mean?

**Comment by hacdias** [comment]
Due to the lack of response and not being able to reproduce this, I am closing this issue. If you have further comments, please add a comment here.

**Comment by downerxl** [comment]
Same problem, got "caught signal, shutting down" then docker restart, every 3-4 minutes. On my Zspace NAS.
