### ISSUE TITLE
BugReport

### ISSUE THREAD

**Issue by alexcmx** [hacdias/webdav#195]
I've set up only read writes, but I'm still able to create files inside directory
![Снимок экрана от 2024-11-03 18-13-24](https://github.com/user-attachments/assets/dbbd485c-a10e-4810-8aa9-d9b359b5d19b)
![Снимок экрана от 2024-11-03 18-13-03](https://github.com/user-attachments/assets/ba41156d-ddab-4754-b3ce-833f7729d8e0)

**Comment by hacdias** [comment]
The path in the `rules` is relative to the directory `directory`. 

Instead of `/media/storage/shared/docs`, you should use `/docs`. Similar to `/drop`.
