### ISSUE TITLE
网页浏览器无法直接访问服务器文件

### ISSUE THREAD

**Issue by woshixiguapi** [hacdias/webdav#196]
网页浏览器无法直接访问服务器文件，显示为一个XML文件的内容，希望能实现利用网页浏览器直接访问服务器文件，这样手机就不用另外再安装一个客户端app了。谢谢！
![Screenshot_2024-11-09-15-22-44-98_439a3fec0400f8974d35eed09a31f914](https://github.com/user-attachments/assets/96898a32-09a5-4ee8-bcaf-0ae966b6022a)

**Comment by hacdias** [comment]
We don't have any plans to support a direct interface on the browser. You should instead use a WebDAV Client, for example: https://github.com/fstanis/awesome-webdav#desktop-apps
