### ISSUE TITLE
The WebDAV feature does not support PUT with Ranges

### ISSUE THREAD

**Issue by oorrnae** [hacdias/webdav#203]
https://www.ietf.org/archive/id/draft-ietf-httpapi-patch-byterange-02.html

https://github.com/owncloud/core/issues/1051

**Comment by hacdias** [comment]
@oorrnae if you want such functionality, you should open an issue on Go's repository: https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+x%2Fnet%2Fwebdav

Here it is explained how to proceed: https://cs.opensource.google/go/x/net
