### ISSUE TITLE
Using bcrypt password are much slower compared to plain text

### ISSUE THREAD

**Issue by bramaudi** [hacdias/webdav#206]
Of course when using encryption you are used to be more slower because it run additional process in this case the "compare bcrypt hash"s function, but it feel uncomfortably slow when compared to plain text password.

Perhaps it can be optimized.

**Comment by hacdias** [comment]
The new version has a new `bcrypt` command that you can use to generate an encrypted password with different costs: https://github.com/hacdias/webdav/releases/tag/v5.7.0

**Comment by bramaudi** [comment]
Thanks, that's definitely fixed the problem, performance are much improved. Nice.
