### ISSUE TITLE
Filename truncated after semicolon

### ISSUE THREAD

**Issue by mholt** [hacdias/webdav#29]
I am not sure if the bug is in caddy-webdav or in this lib, but it seems that a filename with a semicolon (`;`) in it gets truncated at the semicolon (the semicolon is also elided) when listing files. Have you encountered this before or is it just me? 😅

**Comment by hacdias** [comment]
![image](https://user-images.githubusercontent.com/5447088/68543381-1fbe9d00-03ae-11ea-9360-5e093ceee111.png)

It is not happening as a standalone. You were referring to the listing, right?

**Comment by mholt** [comment]
Yep! Wow, that's weird, maybe my client has the bug then! I'm using Transmit by Panic. I'll file a report with them then.

Thanks for looking into it, I hadn't considered that...

**Comment by hacdias** [comment]
Nope, I didn't try with `caddy-webdav` but with the webdav binary itself. But, I can try with caddy-webdav. If it fails, it should be a Caddy issue, not webdav 'cause I just call the lib there. Will check tho

**Comment by mholt** [comment]
Thanks. That'd for sure narrow it down between my client or caddy-webdav... or if there's another client I should try I could give it a go.

**Comment by hacdias** [comment]
Thanks @mholt: here's the one I use https://cyberduck.io 😃

**Comment by mholt** [comment]
Ah... indeed, it must be a bug in my client, Transmit. Cyberduck shows the names just fine. Thanks!

**Comment by hacdias** [comment]
No problem Matt! 😄
