### ISSUE TITLE
Feature request: create backup

### ISSUE THREAD

**Issue by kookma** [hacdias/webdav#38]
I use webdav with Tiddlywiki

https://tiddlywiki.com

It is a single file self contain html one can edit it over the http.
When you save a modified file webdav save it correctly!
I wish to be able to create a backup file when I save the file.

In other words

Having test.html open and modify using webdav! how can I make a backup
on every save?

**Comment by hacdias** [comment]
I don't think making backups is in the scope of this project. You could look into programs that watch the file and every time there's a change, do a backup. But that's beyond this project.
