### ISSUE TITLE
Crash when scope is settings to root directory on mac and linux

### ISSUE THREAD

**Issue by chromer030** [hacdias/webdav#41]
Hi & Happy New Year...
Thanks for this great project...
The server doesn't working when scope is set to any of roots directories
I tested it on macOS Catalina and Arch Linux...

because of accessing all partitions and disks i needed to set scope to /Volumes/ on Catalina but server doesn't work , even i tried it on Arch Linux and Manjaro ( settings to /mnt/ or /  )  but when scope was set to root directories it doesn't work at all , but work in sub-directories...
Thanks again

**Comment by hacdias** [comment]
Please reopen if this is still the case.
