### ISSUE TITLE
Windows 10 cannot map webdav as a drive

### ISSUE THREAD

**Issue by zssng** [hacdias/webdav#54]
I test the service with cyberduck,everything is ok,but win10 cannot map webdav as a drive ,keep ask for user name & password

**Comment by shyim** [comment]
Works for me without any problems 🤔

**Comment by dongshunyao** [comment]
> I test the service with cyberduck,everything is ok,but win10 cannot map webdav as a drive ,keep ask for user name & password

Http? Win10 only support https. Try to enable tls?

**Comment by zssng** [comment]
> > I test the service with cyberduck,everything is ok,but win10 cannot map webdav as a drive ,keep ask for user name & password
> 
> Http? Win10 only support https. Try to enable tls?

I use windows server to achive this and tls not enabled
