### ISSUE TITLE
Is there any chance add an option to config log file path?

### ISSUE THREAD

**Issue by smasterfree** [hacdias/webdav#62]
Currently we could not log to file, which is inconvenient for monitoring error log or let fail2ban to ban some attack ips.

thank you !

**Comment by flacname** [comment]
we need log to file . log_format does not work without console.

**Comment by xiaolei0125** [comment]
need log info to some files

**Comment by mohammed90** [comment]
It logs to `stderr`. If you're running webdav using systemd unit, then fail2ban definitely can monitor those logs. You can also configure systemd units to redirect stderr to a file.
