### ISSUE TITLE
Docker image: webdav exited with code 255

### ISSUE THREAD

**Issue by Bouni** [hacdias/webdav#64]
Hi,

I use the docker image and whenever I restart the host, the webdav container does not come up ans the logs only show `webdav exited with code 255`.

If I then start it manually using `docker-compose up -d`, it starts an everything is fine.

Is there a debug option or some kind of verbosioity settinng to figure out whats going wrong?

**Comment by Mohammed90** [comment]
How are you running the docker-compose setup? Systemd service? If it's a systemd service, please paste the unit file.

 Ideally the host should be sending the stop command to the container rather than just killing it without notification.

**Comment by Bouni** [comment]
To be honest, I can't say. 
I installed docker using the the curl method from get.docker.com and installed docker-compose using pip.
There is no docker-compose systemd service just one for docker.

How can I figure that out?

**Comment by Mohammed90** [comment]
Walk me through how you're running the docker container. Is the systemd service for docker the one for docker's daemon, or did you create one for the webdav container?

**Comment by hacdias** [comment]
Please reopen if this is still the case.
