### ISSUE TITLE
Start: webdav --config webdav.config  isn't reading the config file

### ISSUE THREAD

**Issue by oricalcum4713** [hacdias/webdav#72]
I'm testing webdav on my centos 7.6 Linux VM.
Startup with options is working, sample:
$ ./webdav -p 8080 --auth=false --tls=false
Listening on [::]:8080
So i can connect via Win explorer.

Startup with webdav.config isn't reading the config file, sample:
$ ./webdav --config ./webdav.config
Listening on [::]:42106

webdav.config

# Server related settings
address: 10.116.7.161
port: 80
auth: false
tls: false
cert: cert.pem
key: key.pem
prefix: /

# Default user settings (will be merged)
scope: .
modify: true
rules: []

# CORS configuration
cors:
  enabled: true
  credentials: true
  allowed_headers:
    - Depth
  allowed_hosts:
    - http://localhost:80
  allowed_methods:
    - GET
  exposed_headers:
    - Content-Length
    - Content-Range

users:
  - username: admin
    password: admin
    scope: /a/different/path
  - username: encrypted
    password: "{bcrypt}$2y$10$zEP6oofmXFeHaeMfBNLnP.DO8m.H.Mwhd24/TOX2MWLxAExXi4qgi"
  - username: "{env}ENV_USERNAME"
    password: "{env}ENV_PASSWORD"
  - username: basic
    password: basic
    modify:   false
    rules:
      - regex: false
        allow: false
        path: /some/file
      - path: /public/access/
        modify: true

**Comment by oricalcum4713** [comment]
It works now. 
One problem was the {env} entries in the config.file
The second problem was the sample for the service startup with the bad named "config.file"

**Comment by Mohammed90** [comment]
> It works now. 

Glad it's working now! I was confused to see this report.

> One problem was the {env} entries in the config.file
> The second problem was the sample for the service startup with the bad named "config.file"

The file name you're feeding into the command line shouldn't rely on what the sample file in this repo is named. It should rely on what your file name is.
