### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [hacdias/webdav#77]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by Mohammed90** [comment]
I'm a collaborator on this repo. Until we publish a `SECURITY.md` file, can you message me? You can DM me on Twitter

**Comment by zidingz** [comment]
Hey @Mohammed90, thanks for your reply!

While I see that you're one of the top contributors to this repository and I personally harbour little doubt of your association, we can only disclose details as instructed by a security policy i.e. created by a user with write-access. If it's possible, kindly consider adding an email to this simple [draft](https://github.com/hacdias/webdav/pull/81) of a security policy and we'll shoot an email over right away.
