### ISSUE TITLE
It is not possible to open a large file or save it to the local disk.

### ISSUE THREAD

**Issue by oricalcum4713** [hacdias/webdav#92]
It's not possible to open large files.
Tried to open it by notepad++ , error message
![image](https://user-images.githubusercontent.com/86006067/134340378-827135cf-5d8f-46eb-9bf2-4d67adf5869d.png)

Than i tried to save such a large file on my local disk, i get this error:
![image](https://user-images.githubusercontent.com/86006067/134340613-9e4b08f4-0ce6-4435-ba79-d9a14925acdd.png)

Are there file size limitations?

Regards
Ori

**Comment by oricalcum4713** [comment]
I made some further checks.
It now looks more like we have reached Windows limits here
https://docs.microsoft.com/en-us/troubleshoot/windows-client/networking/cannot-access-webdav-web-folder
Winscp is working well.

**Comment by Mohammed90** [comment]
So that doesn't seem to be an issue with this repo. Closing unless you show it's an issue with the code here.
