### ISSUE TITLE
Windows reporting malware in windows-386-webdav.zip on Windows 10

### ISSUE THREAD

**Issue by AnthonyMuscio** [hacdias/webdav#93]
Windows reporting malware in windows-386-webdav.zip on Windows 10 and deletes webdave.exe
![Snag_708b61d](https://user-images.githubusercontent.com/31584658/134345767-e5edb782-d90d-4d6f-bbf8-5ef3f9a9009b.png)

This seems like an ideal companion to tiddlywiki.com so I hope it can be fixed.

**Comment by AnthonyMuscio** [comment]
FYI: However the amd64 version is working on my intel windows 10

**Comment by Mohammed90** [comment]
This is definitely false-positive. This is frequent with dummy virus scanners and Go binaries, see:
https://golang.org/doc/faq#virus
