### ISSUE TITLE
程序启动后，用浏览器登录后显示如下内容，求助！

### ISSUE THREAD

**Issue by hzl88688** [hacdias/webdav#96]
浏览器提示：
This XML file does not appear to have any style information associated with it. The document tree is shown below.

**Comment by marcoysg** [comment]
建议用映射一个盘作为文件夹访问。

**Comment by ErDongChen1973** [comment]
在window下面，映射一个盘符也出错

**Comment by liangchaofu** [comment]
同样问题，我是用在openwrt路由器上的

**Comment by ErDongChen1973** [comment]
> 同样问题，我是用在openwrt路由器上的

我改用chfs了，感觉还行！

**Comment by VergilGao** [comment]
浏览器显示的是你webdav服务器目录结构的xml文件，你得用一个webdav客户端来访问。
此外windows映射需要你的webdav通过一个反代服务器启用ssl或者自己配置ssl

**Comment by hacdias** [comment]
Exactly what @VergilGao said!
