### ISSUE TITLE
"modify: false" doesn't work?

### ISSUE THREAD

**Issue by CatSamaDD** [hacdias/webdav#97]
users:
  - username: user
    password: "123456"
    scope: /data
    modify: false

Sorry for my poor English.
When I set “modify: false” , I can connect my webdav server,but I can still create ,edit , delete  files .
What I want is all the "/data" is readonly.
What should I do? Thanks.

**Comment by CatSamaDD** [comment]
the only different between "modify: false“ and "modify: true" is I can't create folder when I set "modify: false“

**Comment by andreymal** [comment]
It's so strange, the modification methods are marked as `noModification`...

https://github.com/hacdias/webdav/blob/8a8650d9b224263080e49c3acde8aad2e3a9d040/lib/webdav.go#L110-L118

**Comment by mohammed90** [comment]
> It's so strange, the modification methods are marked as `noModification`...
> 
> https://github.com/hacdias/webdav/blob/8a8650d9b224263080e49c3acde8aad2e3a9d040/lib/webdav.go#L110-L118

I suspected that code is wrong in my local copy, and we discussed it briefly on this commit:

https://github.com/hacdias/webdav/commit/9a4b378b32ea04b5c45b727713837e34435d0ef5#comments

I'm quite busy during this time and won't get around to shooting a fix soon. Anyone is free to shoot the PR, and I'll gladly review it and merge it.

**Comment by zailushang2008** [comment]
Has this been addressed in the official version？

**Comment by zailushang2008** [comment]
Has this been addressed in the docker version？
